
[grenade]
	#Whether grenade explosion can damage blocks (if it can)
	grenadeExplosionBlockDamage = false

[melee]
	#Whether melee items consume durability on attack
	meleeItemConsumeDurability = false
	#when target's invulnerable tick is less than this value, melee attack will ignore it
	#Range: 0 ~ 100
	meleeIgnoreInvulnerableTickThreshold = 20

